// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: courses.sql

package coursessqlc

import (
	"context"
	"database/sql"
	"time"
)

const createCourse = `-- name: CreateCourse :execresult
INSERT INTO course (title, is_active, is_dirty, updated_at)
VALUES (
  ?,
  ?,
  ?,
  ?
)
`

type CreateCourseParams struct {
	Title     string
	IsActive  bool
	IsDirty   bool
	UpdatedAt time.Time
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCourse,
		arg.Title,
		arg.IsActive,
		arg.IsDirty,
		arg.UpdatedAt,
	)
}
