// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: lti.sql

package ltisqlc

import (
	"context"
)

const createLTICourseLink = `-- name: CreateLTICourseLink :exec
INSERT INTO lti_course_link (tenant_id, context_id, course_id)
VALUES (?, ?, ?)
`

type CreateLTICourseLinkParams struct {
	TenantID  uint64
	ContextID string
	CourseID  uint64
}

func (q *Queries) CreateLTICourseLink(ctx context.Context, arg CreateLTICourseLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLTICourseLink, arg.TenantID, arg.ContextID, arg.CourseID)
	return err
}

const createLTIUserLink = `-- name: CreateLTIUserLink :exec
INSERT INTO lti_user_link (sub, issuer, user_id)
VALUES (?, ?, ?)
`

type CreateLTIUserLinkParams struct {
	Sub    string
	Issuer string
	UserID uint64
}

func (q *Queries) CreateLTIUserLink(ctx context.Context, arg CreateLTIUserLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLTIUserLink, arg.Sub, arg.Issuer, arg.UserID)
	return err
}

const createRegistration = `-- name: CreateRegistration :exec
INSERT INTO registration (
  issuer,
  client_id,
  tenant_id,
  login_auth_endpoint,
  jwk_endpoint,
  service_auth_endpoint,
  service_logout_endpoint
)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateRegistrationParams struct {
	Issuer                string
	ClientID              string
	TenantID              uint64
	LoginAuthEndpoint     string
	JwkEndpoint           string
	ServiceAuthEndpoint   string
	ServiceLogoutEndpoint string
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, createRegistration,
		arg.Issuer,
		arg.ClientID,
		arg.TenantID,
		arg.LoginAuthEndpoint,
		arg.JwkEndpoint,
		arg.ServiceAuthEndpoint,
		arg.ServiceLogoutEndpoint,
	)
	return err
}

const getLTICourseLinkByTenantAndContext = `-- name: GetLTICourseLinkByTenantAndContext :one
SELECT tenant_id, context_id, course_id
FROM lti_course_link
WHERE tenant_id = ?
  AND context_id = ?
LIMIT 1
`

type GetLTICourseLinkByTenantAndContextParams struct {
	TenantID  uint64
	ContextID string
}

type GetLTICourseLinkByTenantAndContextRow struct {
	TenantID  uint64
	ContextID string
	CourseID  uint64
}

func (q *Queries) GetLTICourseLinkByTenantAndContext(ctx context.Context, arg GetLTICourseLinkByTenantAndContextParams) (GetLTICourseLinkByTenantAndContextRow, error) {
	row := q.db.QueryRowContext(ctx, getLTICourseLinkByTenantAndContext, arg.TenantID, arg.ContextID)
	var i GetLTICourseLinkByTenantAndContextRow
	err := row.Scan(&i.TenantID, &i.ContextID, &i.CourseID)
	return i, err
}

const getLTIUserLinkBySubAndIssuer = `-- name: GetLTIUserLinkBySubAndIssuer :one
SELECT sub, issuer, user_id
FROM lti_user_link
WHERE sub = ?
  AND issuer = ?
LIMIT 1
`

type GetLTIUserLinkBySubAndIssuerParams struct {
	Sub    string
	Issuer string
}

type GetLTIUserLinkBySubAndIssuerRow struct {
	Sub    string
	Issuer string
	UserID uint64
}

func (q *Queries) GetLTIUserLinkBySubAndIssuer(ctx context.Context, arg GetLTIUserLinkBySubAndIssuerParams) (GetLTIUserLinkBySubAndIssuerRow, error) {
	row := q.db.QueryRowContext(ctx, getLTIUserLinkBySubAndIssuer, arg.Sub, arg.Issuer)
	var i GetLTIUserLinkBySubAndIssuerRow
	err := row.Scan(&i.Sub, &i.Issuer, &i.UserID)
	return i, err
}

const getRegistrationByIssuerAndClientID = `-- name: GetRegistrationByIssuerAndClientID :one
SELECT issuer, client_id, tenant_id, login_auth_endpoint, jwk_endpoint, service_auth_endpoint, service_logout_endpoint
FROM registration
WHERE issuer = ?
  AND client_id = ?
LIMIT 1
`

type GetRegistrationByIssuerAndClientIDParams struct {
	Issuer   string
	ClientID string
}

type GetRegistrationByIssuerAndClientIDRow struct {
	Issuer                string
	ClientID              string
	TenantID              uint64
	LoginAuthEndpoint     string
	JwkEndpoint           string
	ServiceAuthEndpoint   string
	ServiceLogoutEndpoint string
}

func (q *Queries) GetRegistrationByIssuerAndClientID(ctx context.Context, arg GetRegistrationByIssuerAndClientIDParams) (GetRegistrationByIssuerAndClientIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationByIssuerAndClientID, arg.Issuer, arg.ClientID)
	var i GetRegistrationByIssuerAndClientIDRow
	err := row.Scan(
		&i.Issuer,
		&i.ClientID,
		&i.TenantID,
		&i.LoginAuthEndpoint,
		&i.JwkEndpoint,
		&i.ServiceAuthEndpoint,
		&i.ServiceLogoutEndpoint,
	)
	return i, err
}

const updateRegistration = `-- name: UpdateRegistration :execrows
UPDATE registration
SET
  tenant_id = ?,
  login_auth_endpoint = ?,
  jwk_endpoint = ?,
  service_auth_endpoint = ?,
  service_logout_endpoint = ?
WHERE issuer = ?
  AND client_id = ?
`

type UpdateRegistrationParams struct {
	TenantID              uint64
	LoginAuthEndpoint     string
	JwkEndpoint           string
	ServiceAuthEndpoint   string
	ServiceLogoutEndpoint string
	Issuer                string
	ClientID              string
}

func (q *Queries) UpdateRegistration(ctx context.Context, arg UpdateRegistrationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRegistration,
		arg.TenantID,
		arg.LoginAuthEndpoint,
		arg.JwkEndpoint,
		arg.ServiceAuthEndpoint,
		arg.ServiceLogoutEndpoint,
		arg.Issuer,
		arg.ClientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
