// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package ltisqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Course struct {
	ID        uint64
	Title     string
	TenantID  sql.NullInt64
	IsActive  bool
	IsDirty   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FileItem struct {
	ID           uint64
	CourseID     uint64
	ReviewedByID sql.NullInt64
	ReviewedOn   sql.NullTime
	Reviewed     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type LmsObjectMapping struct {
	InternalID  uint64
	ObjectType  string
	LmsKey      string
	MappingJson json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type LmsUserCredential struct {
	ID             uint64
	UserID         uint64
	LmsKey         string
	SchemaName     string
	CredentialJson json.RawMessage
	ExpiresAt      sql.NullTime
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type LmsUserMapping struct {
	UserID         uint64
	LmsKey         string
	ExternalUserID sql.NullString
	ApiDomain      sql.NullString
	Metadata       json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type LtiCourseLink struct {
	TenantID  uint64
	ContextID string
	CourseID  uint64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LtiUserLink struct {
	Sub       string
	Issuer    string
	UserID    uint64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Registration struct {
	ID                    uint64
	Issuer                string
	ClientID              string
	TenantID              uint64
	LoginAuthEndpoint     string
	JwkEndpoint           string
	ServiceAuthEndpoint   string
	ServiceLogoutEndpoint string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Tenant struct {
	ID        uint64
	LmsKey    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          uint64
	Username    string
	Name        string
	Preferences json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UserSession struct {
	Uuid      string
	Data      json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt sql.NullTime
}
