// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: lms.sql

package lmssqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getActiveLMSUserCredentialByUserID = `-- name: GetActiveLMSUserCredentialByUserID :one
SELECT user_id, lms_key, credential_json, expires_at, is_active, created_at, updated_at
FROM lms_user_credential
WHERE user_id = ?
  AND is_active = 1
LIMIT 1
`

type GetActiveLMSUserCredentialByUserIDRow struct {
	UserID         uint64
	LmsKey         string
	CredentialJson json.RawMessage
	ExpiresAt      sql.NullTime
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetActiveLMSUserCredentialByUserID(ctx context.Context, userID uint64) (GetActiveLMSUserCredentialByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveLMSUserCredentialByUserID, userID)
	var i GetActiveLMSUserCredentialByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.LmsKey,
		&i.CredentialJson,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLMSObjectMappingByTypeAndInternalID = `-- name: GetLMSObjectMappingByTypeAndInternalID :one
SELECT lms_key, mapping_json
FROM lms_object_mapping
WHERE object_type = ?
  AND internal_id = ?
LIMIT 1
`

type GetLMSObjectMappingByTypeAndInternalIDParams struct {
	ObjectType string
	InternalID uint64
}

type GetLMSObjectMappingByTypeAndInternalIDRow struct {
	LmsKey      string
	MappingJson json.RawMessage
}

func (q *Queries) GetLMSObjectMappingByTypeAndInternalID(ctx context.Context, arg GetLMSObjectMappingByTypeAndInternalIDParams) (GetLMSObjectMappingByTypeAndInternalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLMSObjectMappingByTypeAndInternalID, arg.ObjectType, arg.InternalID)
	var i GetLMSObjectMappingByTypeAndInternalIDRow
	err := row.Scan(&i.LmsKey, &i.MappingJson)
	return i, err
}

const getLMSUserMappingByUserID = `-- name: GetLMSUserMappingByUserID :one
SELECT user_id, lms_key, COALESCE(external_user_id, ''), COALESCE(api_domain, ''), COALESCE(metadata, '{}'), created_at, updated_at
FROM lms_user_mapping
WHERE user_id = ?
LIMIT 1
`

type GetLMSUserMappingByUserIDRow struct {
	UserID         uint64
	LmsKey         string
	ExternalUserID string
	ApiDomain      string
	Metadata       json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetLMSUserMappingByUserID(ctx context.Context, userID uint64) (GetLMSUserMappingByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLMSUserMappingByUserID, userID)
	var i GetLMSUserMappingByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.LmsKey,
		&i.ExternalUserID,
		&i.ApiDomain,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLMSUserCredential = `-- name: UpsertLMSUserCredential :exec
INSERT INTO lms_user_credential (
  user_id,
  lms_key,
  schema_name,
  credential_json,
  expires_at,
  is_active,
  created_at,
  updated_at
)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  1,
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  schema_name = VALUES(schema_name),
  credential_json = VALUES(credential_json),
  expires_at = VALUES(expires_at),
  is_active = 1,
  updated_at = NOW()
`

type UpsertLMSUserCredentialParams struct {
	UserID         uint64
	LmsKey         string
	SchemaName     string
	CredentialJson json.RawMessage
	ExpiresAt      sql.NullTime
}

func (q *Queries) UpsertLMSUserCredential(ctx context.Context, arg UpsertLMSUserCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertLMSUserCredential,
		arg.UserID,
		arg.LmsKey,
		arg.SchemaName,
		arg.CredentialJson,
		arg.ExpiresAt,
	)
	return err
}

const upsertLMSUserMapping = `-- name: UpsertLMSUserMapping :exec
INSERT INTO lms_user_mapping (
  user_id,
  lms_key,
  external_user_id,
  api_domain,
  metadata,
  created_at,
  updated_at
)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  lms_key = VALUES(lms_key),
  external_user_id = VALUES(external_user_id),
  api_domain = VALUES(api_domain),
  metadata = VALUES(metadata),
  updated_at = NOW()
`

type UpsertLMSUserMappingParams struct {
	UserID         uint64
	LmsKey         string
	ExternalUserID sql.NullString
	ApiDomain      sql.NullString
	Metadata       json.RawMessage
}

func (q *Queries) UpsertLMSUserMapping(ctx context.Context, arg UpsertLMSUserMappingParams) error {
	_, err := q.db.ExecContext(ctx, upsertLMSUserMapping,
		arg.UserID,
		arg.LmsKey,
		arg.ExternalUserID,
		arg.ApiDomain,
		arg.Metadata,
	)
	return err
}
