// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: files.sql

package filessqlc

import (
	"context"
	"database/sql"
)

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM file_item
WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, course_id, reviewed_by_id, reviewed_on, reviewed
FROM file_item
WHERE id = ?
LIMIT 1
`

type GetFileByIDRow struct {
	ID           uint64
	CourseID     uint64
	ReviewedByID sql.NullInt64
	ReviewedOn   sql.NullTime
	Reviewed     bool
}

func (q *Queries) GetFileByID(ctx context.Context, id uint64) (GetFileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i GetFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ReviewedByID,
		&i.ReviewedOn,
		&i.Reviewed,
	)
	return i, err
}

const updateFile = `-- name: UpdateFile :exec
UPDATE file_item
SET
  course_id = ?,
  reviewed_by_id = ?,
  reviewed_on = ?,
  reviewed = ?
WHERE id = ?
`

type UpdateFileParams struct {
	CourseID     uint64
	ReviewedByID sql.NullInt64
	ReviewedOn   sql.NullTime
	Reviewed     bool
	ID           uint64
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) error {
	_, err := q.db.ExecContext(ctx, updateFile,
		arg.CourseID,
		arg.ReviewedByID,
		arg.ReviewedOn,
		arg.Reviewed,
		arg.ID,
	)
	return err
}
