// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: sessions.sql

package authsqlc

import (
	"context"
	"encoding/json"
)

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM user_session
WHERE uuid = ?
`

func (q *Queries) DeleteSessionByID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByID, uuid)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT uuid, data
FROM user_session
WHERE uuid = ?
LIMIT 1
`

type GetSessionByIDRow struct {
	Uuid string
	Data json.RawMessage
}

func (q *Queries) GetSessionByID(ctx context.Context, uuid string) (GetSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, uuid)
	var i GetSessionByIDRow
	err := row.Scan(&i.Uuid, &i.Data)
	return i, err
}
