// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package userssqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO user (username, name, preferences)
VALUES (?, ?, ?)
`

type CreateUserParams struct {
	Username    string
	Name        string
	Preferences json.RawMessage
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Username, arg.Name, arg.Preferences)
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, name, preferences
FROM user
WHERE id = ?
LIMIT 1
`

type GetUserByIDRow struct {
	ID          uint64
	Username    string
	Name        string
	Preferences json.RawMessage
}

func (q *Queries) GetUserByID(ctx context.Context, id uint64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Preferences,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE user
SET
  username = ?,
  name = ?,
  preferences = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Username    string
	Name        string
	Preferences json.RawMessage
	ID          uint64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Name,
		arg.Preferences,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
